# Generated by Django 3.0.1 on 2020-01-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('week', models.CharField(max_length=50)),
                ('pdf', models.FileField(upload_to='resources/pdfs/')),
            ],
        ),
    ]
